#!/usr/bin/env python3
import gi
import requests
import urllib
import os

gi.require_version('Playerctl', '1.0')

from gi.repository import Playerctl, GLib

player = Playerctl.Player()

def on_metadata(player, e):
    if 'xesam:artist' in e.keys() and 'xesam:title' in e.keys():
        print('Now playing:')
        msg = urllib.parse.quote('♫ {artist} - {title}'.format(artist=e['xesam:artist'][0], title=e['xesam:title']))
        print(msg)
        requests.get('https://slack.com/api/users.profile.set?token='+os.environ['SLACK_TOKEN']+'&user='+os.environ['SLACK_USER']+'&pretty=1&profile={"title":"'+msg+'"}')

player.on('metadata', on_metadata)

main = GLib.MainLoop()
main.run()
