#!/bin/bash

DIST=${DIST:-"teamscale-munichre"}
BRANCH=${BRANCH:-`git rev-parse --abbrev-ref HEAD`}
TOKEN=`cat ~/.bin/ts-build.token`

echo "Building dist $DIST for branch $BRANCH"

curl -X POST --url https://git.cqse.eu/api/v4/projects/13/trigger/pipeline \
	-F token=$TOKEN \
	-F 'variables[DIST]=teamscale-munichre' \
	-F "ref=`git rev-parse --abbrev-ref HEAD`"
