#!/bin/bash

DIST=${DIST:-"teamscale-munichre"}
BRANCH=${BRANCH:-`git rev-parse --abbrev-ref HEAD`}

echo "Building dist $DIST for branch $BRANCH"

curl -X POST --url https://git.cqse.eu/api/v4/projects/13/trigger/pipeline \
	-F token=b9f21e76680b9acde51c62a99b9de6 \
	-F 'variables[DIST]=teamscale-munichre' \
	-F "ref=`git rev-parse --abbrev-ref HEAD`"
